// Code generated by "stringer -type=AWSServiceName"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Route53-0]
	_ = x[IAM-1]
	_ = x[EKS-2]
	_ = x[SSM-3]
	_ = x[EC2-4]
	_ = x[RDS-5]
	_ = x[SSOAdmin-6]
	_ = x[IdentityStore-7]
	_ = x[SNS-8]
	_ = x[S3-9]
	_ = x[CloudFront-10]
	_ = x[ELB-11]
	_ = x[ELBV2-12]
	_ = x[ASG-13]
	_ = x[Lambda-14]
	_ = x[ResourceGroupsTaggingAPI-15]
}

const _AWSServiceName_name = "Route53IAMEKSSSMEC2RDSSSOAdminIdentityStoreSNSS3CloudFrontELBELBV2ASGLambdaResourceGroupsTaggingAPI"

var _AWSServiceName_index = [...]uint8{0, 7, 10, 13, 16, 19, 22, 30, 43, 46, 48, 58, 61, 66, 69, 75, 99}

func (i AWSServiceName) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AWSServiceName_index)-1 {
		return "AWSServiceName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AWSServiceName_name[_AWSServiceName_index[idx]:_AWSServiceName_index[idx+1]]
}
