// Code generated by "stringer -type=ResourceType"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Route53_zone-0]
	_ = x[Route53_record-1]
	_ = x[IAM_policy-2]
	_ = x[IAM_user-3]
	_ = x[IAM_group-4]
	_ = x[SSM_parameter-5]
	_ = x[Security_group-6]
	_ = x[Security_group_rule-7]
	_ = x[EKS_cluster-8]
	_ = x[SSOAdmin_permission_set-9]
	_ = x[Identitystore_user-10]
	_ = x[Identitystore_group-11]
}

const _ResourceType_name = "Route53_zoneRoute53_recordIAM_policyIAM_userIAM_groupSSM_parameterSecurity_groupSecurity_group_ruleEKS_clusterSSOAdmin_permission_setIdentitystore_userIdentitystore_group"

var _ResourceType_index = [...]uint8{0, 12, 26, 36, 44, 53, 66, 80, 99, 110, 133, 151, 170}

func (i ResourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResourceType_index)-1 {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[idx]:_ResourceType_index[idx+1]]
}
