// Code generated by "stringer -type=ResourceType"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Route53_zone-0]
	_ = x[Route53_record-1]
	_ = x[IAM_policy-2]
	_ = x[IAM_user-3]
	_ = x[IAM_group-4]
	_ = x[SSM_parameter-5]
	_ = x[Security_group-6]
	_ = x[Security_group_rule-7]
	_ = x[EKS_cluster-8]
	_ = x[EKS_node_group-9]
	_ = x[SSOAdmin_permission_set-10]
	_ = x[Identitystore_user-11]
	_ = x[Identitystore_group-12]
	_ = x[Instance-13]
	_ = x[Eip-14]
	_ = x[DB_instance-15]
	_ = x[RDS_cluster-16]
	_ = x[SNS_topic-17]
	_ = x[SNS_subscription-18]
	_ = x[S3_bucket-19]
	_ = x[CloudFront_distribution-20]
	_ = x[ELB_load_balancer-21]
	_ = x[ELBV2_load_balancer-22]
}

const _ResourceType_name = "Route53_zoneRoute53_recordIAM_policyIAM_userIAM_groupSSM_parameterSecurity_groupSecurity_group_ruleEKS_clusterEKS_node_groupSSOAdmin_permission_setIdentitystore_userIdentitystore_groupInstanceEipDB_instanceRDS_clusterSNS_topicSNS_subscriptionS3_bucketCloudFront_distributionELB_load_balancerELBV2_load_balancer"

var _ResourceType_index = [...]uint16{0, 12, 26, 36, 44, 53, 66, 80, 99, 110, 124, 147, 165, 184, 192, 195, 206, 217, 226, 242, 251, 274, 291, 310}

func (i ResourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResourceType_index)-1 {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[idx]:_ResourceType_index[idx+1]]
}
